/*
-- Query: SELECT * FROM hotel_db.room
LIMIT 0, 1000

-- Date: 2019-05-24 09:11
*/
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (1,'double',80,'201','standard','available','the perfect spot to hold your meeting or simply enjoy the unique floor plan for your overnight stay in Urbandale, IA.','This 340 square foot suite features a king size bed, 37” flat screen LCD television with high definition channels, board room table with seating for six, wet bar with fridge and microwave.','/static/images/a1');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (2,'king',100,'102','suits','reserved','Feel refreshed in this standard 340 square foot room featuring two queen beds with luxurious crisp, white cotton Villa di Lusso bedding, 37” LCD flat screen television with high definition channels, modern desk workspace, and oversized chair with ottoman.','The large bathroom offers a shower/tub and Carrera marble vanity. The featured Beekman 1802™ bath amenities will leave you feeling refreshed and renewed.','/static/images/b1');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (3,'king',100,'101','suits','reserved','Feel refreshed in this standard 340 square foot room featuring two queen beds with luxurious crisp, white cotton Villa di Lusso bedding, 37” LCD flat screen television with high definition channels, modern desk workspace, and oversized chair with ottoman.','The large bathroom offers a shower/tub and Carrera marble vanity. The featured Beekman 1802™ bath amenities will leave you feeling refreshed and renewed.','/static/images/b2');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (9,'King',100,'mum hall','Suits','Reserved','Feel refreshed in this standard 340 square foot room featuring two queen beds with luxurious crisp, white cotton Villa di Lusso bedding, 37” LCD flat screen television with high definition channels, modern desk workspace, and oversized chair with ottoman.','The large bathroom offers a shower/tub and Carrera marble vanity. The featured Beekman 1802™ bath amenities will leave you feeling refreshed and renewed.','/static/images/b3');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (10,'Twin',40,'106','Single','Reserved','Room is equipped with state of the art technology including complimentary high-speed wired and wireless internet, Starbucks™ in-room coffee pods with maker and fridge.','','/ima');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (11,'Queen',90,'new room','Single','Available','this is new room','features of new room','/static/images');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (12,'King',100,'107','Suits','Available','Feel refreshed in this standard 340 square foot room featuring two queen beds with luxurious crisp, white cotton Villa di Lusso bedding, 37” LCD flat screen television with high definition channels, modern desk workspace, and oversized chair with ottoman.','The large bathroom offers a shower/tub and Carrera marble vanity. The featured Beekman 1802™ bath amenities will leave you feeling refreshed and renewed.','/static/images/b2');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (14,'King',100,'105','Suits','Available','Room is equipped with state of the art technology including complimentary high-speed wired and wireless internet, Starbucks™ in-room coffee pods with maker and fridge.','This standard king room features a modern desk workspace and oversized chair with ottoman.','/static/images/a2');
INSERT INTO `` (`id`,`bed_type`,`price`,`room_number`,`room_type`,`status`,`description`,`features`,`image_location`) VALUES (15,'King',100,'103','Single','Available','Feel refreshed in this standard 340 square foot room featuring two queen beds with luxurious crisp, white cotton Villa di Lusso bedding, 37” LCD flat screen television with high definition channels, modern desk workspace, and oversized chair with ottoman.','The large bathroom offers a shower/tub and Carrera marble vanity. The featured Beekman 1802™ bath amenities will leave you feeling refreshed and renewed.','/static/images/b2');
